

configfile: os.path.join(workflow.basedir, '../', 'config', 'config.yaml')

outTouch = os.path.join(config['output'], config['input'])

rule all:
    input:
        outTouch

rule yeet:
    output:
        touch(outTouch)
